import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider as JotaiProvider } from "jotai";
import "./globals.css";
import { dogImage, myStore } from "~/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const image = await myStore.get(dogImage);

  return (
    <html lang="en">
      <body className={inter.className}>
        <JotaiProvider>
          {!!image && Object.keys(image).length > 0 ? (
            <h1>{image.message}</h1>
          ) : (
            <h1>No picture in layout</h1>
          )}
          {children}
        </JotaiProvider>
      </body>
    </html>
  );
}
